### ISSUE TITLE
Fetch contact data from Github

### ISSUE THREAD

**Issue by amy-lei** [amy-lei/dashboard#15]
We should further discussion how to split all this contact data into posts. But here are some proposals for now (where each bullet is its own post):

### Larger but general:
- MLH Staff (and their roles if possible)
- Pods (their mascot, number, mentor, and repos) 
- All MLH Fellows (and their pods) 

### Smaller, but multiple
- MLH Staff
- Pods and their members and mentor
- Repos by language

**Comment by rch-liu** [comment]
Feature added here: https://github.com/amy-lei/dashboard/pull/9
