### ISSUE TITLE
Parse Youtube links & Github issues/PRs

### ISSUE THREAD

**Issue by amy-lei** [amy-lei/dashboard#19]
For good user experience, it'd be best if the user can simply add a link for the post instead of manually filling out the title, description, timestamp, etc. It's possible by using regex to parse the link for the video id and fetching from youtube data api.

[Help on the regex](https://stackoverflow.com/questions/3452546/how-do-i-get-the-youtube-video-id-from-a-url)

**Comment by amy-lei** [comment]
Note: best to do this in the backend

**Comment by yahengsu** [comment]
also parse github links in backend

**Comment by yahengsu** [comment]
#24
